2 Updates 1 Addition
SlackBuildsOrg/slackbuilds pull request #1281
Opened 2022-03-02 03:08 UTC by bassmadrigal

These updates/addition are to get pitivi working on 15.0 with the newer gst version.

libraries/gsound: New dependency for pitivi not already on SBo.
libraries/gst-editing-services: renamed from gstreamer-editing-services to match upstream name and version bumped to match  15.0's gstreamer version.
multimedia/pitivi: version bump to latest version

I imagine both pitivi and gstreamer-editing-services were ftbfs and this should fix them.

2022-03-02 07:03 UTC, bassmadrigal commented
Got another version bump done for puddletag and then I realized I kept the PRGNAM and short desc at the top of the README for gsound.

2022-03-02 14:21 UTC, willysr commented
As for gsound, can you make it comply with our newest template?
https://git.slackbuilds.org/templates/tree/meson-template.SlackBuild
It should use /bin/bash instead of /bin/sh

You can also remove the unneeded code like the 3 find part

2022-03-02 15:50 UTC, bassmadrigal commented
Oops, apparently I need to update my SlackBuild generator script with the 15.0 templates. Update has been pushed.

2022-03-02 17:25 UTC, bassmadrigal commented
Got a few more simple version bumps.

In the future, would you prefer different updates in a different PR if you haven't merged the initial one yet? I'd like to keep this as easy as possible for you.

2022-03-03 10:11 UTC, aclemons commented
> I imagine both pitivi and gstreamer-editing-services were ftbfs and this should fix them.

Excellent - yes I had pitivi on my list and had seen that basically the only fix was a version bump + new dependencies. Thanks for this.

> In the future, would you prefer different updates in a different PR if you haven't merged the initial one yet? I'd like to keep this as easy as possible for you.

For this PT at least, I think it is sensible to keep it focussed on the pitivi fixes and dependencies

2022-03-03 10:19 UTC, aclemons commented on libraries/gst-editing-services/gst-editing-services.SlackBuild
>  #!/bin/bash
This one ftb for me:

```
[...]
cp: cannot stat 'INSTALL': No such file or directory
```

2022-03-03 10:22 UTC, aclemons requested changes
Could you recheck gst-editing-services?

2022-03-03 15:53 UTC, bassmadrigal commented
> Could you recheck gst-editing-services?

Oops, not sure how that slipped through. It's been updated.

2022-03-04 06:05 UTC, aclemons commented
All merged on my branch now. Thanks!

2022-03-04 06:05 UTC, closed without merging