network/sfeed: Update for 1.6
SlackBuildsOrg/slackbuilds pull request #1814
Opened 2022-08-17 18:52 UTC by isaackwy

2022-08-20 02:01 UTC, aclemons commented on network/sfeed/sfeed.SlackBuild
> +VERSION=${VERSION:-1.6}
This one needs some updates:

```
# sbopkglint ../packages/15.0/x86_64/network/sfeed/*txz
Using tests from /usr/share/sbo-maintainer-tools/sbopkglint.d
Installing ../packages/15.0/x86_64/network/sfeed/sfeed-1.6-x86_64-1_SBo.txz to /tmp/sbopkglint.Fxcb0z ...OK
Running test: 05-basic-sanity...
--- forbidden directory exists: usr/share/doc
FAILED
Running test: 10-docs...OK
Running test: 15-noarch...OK
Running test: 20-arch...OK
Running test: 25-lafiles...OK
Running test: 30-manpages...OK
Running test: 35-desktop...OK
Running test: 40-newconfig...OK
Running test: 45-doinst...OK
Running test: 50-icons...OK
!!! sfeed-1.6-x86_64-1_SBo.txz: 1 failures
```

2022-08-20 02:01 UTC, aclemons requested changes
Could you check the doc dir here please?

2022-08-20 02:58 UTC, isaackwy commented
I fixed the issue.
What was going on was that sfeed built the DOCPREFIX directory at /usr/share/doc/sfeed by default.
I initially addressed this by removing the folder - i.e. `rm -r /usr/share/doc/sfeed'
However, your checks have demonstrated that the above approach was insufficient.
Therefore, I decided to change DOCPREFIX (in make install) to /usr/doc/sfeed-$VERSION

Please check my Slackbuild again.

2022-08-24 21:43 UTC, aclemons commented
All good now. Staged to my branch

2022-08-24 21:43 UTC, closed without merging