Updated to version 10.0
SlackBuildsOrg/slackbuilds pull request #2968
Opened 2023-06-27 01:29 UTC by cduston44

2023-06-30 11:28 UTC, aclemons requested changes

2023-06-30 11:28 UTC, aclemons commented on academic/sage/build-sage.log
Stray log file checked in here.

2023-06-30 11:28 UTC, aclemons commented on academic/sage/sage.SlackBuild
>  # Slackware build script for sage
Can you set the perms back to 644 please?

2023-07-10 00:07 UTC, willysr commented
no update from original maintainer, so closing this one
feel free to resubmit PR when the requested changes has been implemented

2023-07-10 00:07 UTC, closed without merging