Mab974 : update for raku and zef
SlackBuildsOrg/slackbuilds pull request #3479
Opened 2023-10-27 15:59 UTC by mab974

MoarVM, nqp, rakudo --> version 2023.10
zef --> version 0.20.0

2023-10-27 23:56 UTC, aclemons commented
@sbo-bot: build perl/MoarVM

2023-10-27 23:56 UTC, aclemons commented
@sbo-bot: build perl/nqp

2023-10-27 23:57 UTC, aclemons commented
@sbo-bot: build perl/rakudo

2023-10-27 23:57 UTC, aclemons commented
@sbo-bot: build perl/zef

2023-10-28 00:35 UTC, aclemons commented on perl/nqp/nqp.SlackBuild
>  if [ "$ARCH" = "i586" ]; then
@mab974 These empty if/else/elif blocks are invalid shell syntax.

2023-10-28 00:35 UTC, aclemons requested changes
Could you update the arch checking blocks please? Thanks

2023-10-28 04:07 UTC, mab974 commented
My bad, sorry for this.
I’m not familiar with the 'need rework' so I won’t have time to do it before the weekly updates. You can cancel this 'pull request'.
thank you Andrew.

2023-10-28 04:13 UTC, aclemons commented
No problem. We just put the label `Need Rework` on PRs that are waiting for maintainers to make changes, so we know what is left for us the handle and what is waiting on someone else.

I'll close this one - just open another PR when you are ready with your updates.

2023-10-28 04:13 UTC, closed without merging