libraries/tlsh: updated for version 4.12.0
SlackBuildsOrg/slackbuilds pull request #8200
Opened 2024-10-01 14:33 UTC by mattegger

2024-10-01 14:37 UTC, willysr commented on libraries/tlsh/tlsh.SlackBuild
>  BUILD=${BUILD:-2}
You forgot to reset the BUILD

2024-10-01 14:37 UTC, willysr requested changes
please check the BUILD

2024-10-01 15:41 UTC, mattegger commented on libraries/tlsh/tlsh.SlackBuild
> +BUILD=${BUILD:-1}
corrected build number

2024-10-02 05:40 UTC, willysr commented
merged

2024-10-02 05:40 UTC, closed without merging